# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5be40a8834d0386a2941a2ea10311e525121eda3cb5598b3678143cf653fdc4249eb5029da69531a63d49f7a5a9630e272e852448c1c9afaac42dad7c6594d9

test:
  secret_key_base: 596a66a2aa337a2ff9f3d90d5326ef9ea2edda1174f5176c3d908a4359143786c6b0cbfe39594790e5ce76105806967010b1cd37994b4911dae76fe5b8fde74b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
